services:
  dnsdist:
    image: powerdns/dnsdist-20:2.0.0-alpha1
    volumes:
      - ./server.crt:/etc/dnsdist/cert.pem
      - ./server.key:/etc/dnsdist/key.pem
      - ./dnsdist.yml:/etc/dnsdist/dnsdist.yml
    ports:
      - "853:853/tcp"
      - "853:853/udp"
      - "443:443/udp"
      - "5753:53/udp"
      - "5753:53/tcp"
      - "443:443/tcp"
      - "8083:8080/tcp"
    command: ["-C", "/etc/dnsdist/dnsdist.yml"]
